# Generated by Django 5.1.2 on 2024-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptBridgeWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmingquestion',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++'), ('C', 'C')], default='Python', max_length=50),
        ),
    ]
